name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Azure Functions Core Tools
      shell: pwsh
      run: |
        npm install -g azure-functions-core-tools@3 --unsafe-perm true
    - name: Setup .NET SDK 3.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dir
        dotnet restore .
    # - name: Build solution
    #   shell: pwsh
    #   run: |
    #     dir
    #     dotnet build . -c Debug -v minimal
    - name: Test function app (Non-Windows)
      shell: pwsh
      run: |
        dir
        $rootDir = $pwd.Path
        cd ./Client
        # Start-Process -NoNewWindow func start --verbose false
        Start-Process -NoNewWindow func @("start","--verbose","false")
        Start-Sleep -s 60
        cd $rootDir/Test
        dotnet test . -c Debug
        cd $rootDir